# -*- coding: utf-8 -*-
"""reto#6.83

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h4-dCU27ADe17hGM3A8PX2hecqNqOl17
"""

def numeros_(numero_1:float, numero_2:float, numero_3:float, numero_4:float, numero_5: float) -> float:
    promedio_multiplicativo = ((numero_1*numero_2*numero_3*numero_4*numero_5)**0.2)
    return promedio_multiplicativo #se definio la variable para calcular el promedio multiplicativo

if __name__ == "__main__":
  numero_1 = float(input("Ingresa el número 1:"))
  numero_2 = float(input("Ingresa el número 2:"))
  numero_3 = float(input("Ingresa el número 3:"))
  numero_4 = float(input("Ingresa el número 4:"))
  numero_5 = float(input("Ingresa el número 5:"))
  prom_mult = numeros_(numero_1, numero_2, numero_3, numero_4, numero_5)
  print("El promedio multiplicativo de los 5 números es " +str(prom_mult))