# -*- coding: utf-8 -*-
"""reto#6.81

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1keQBCXl7Chexk2zXE53GmxrMWFatSLXi
"""

def numeros(numero_1:float, numero_2:float, numero_3:float, numero_4:float, numero_5: float) -> float:
  promedio = ((numero_1 + numero_2 + numero_3 + numero_4 + numero_5)/5)
  return promedio  #se definio la variable para calcular el promedio


if __name__ == "__main__":
  numero_1 = float(input("Ingresa el número 1:"))
  numero_2 = float(input("Ingresa el número 2:"))
  numero_3 = float(input("Ingresa el número 3:"))
  numero_4 = float(input("Ingresa el número 4:"))
  numero_5 = float(input("Ingresa el número 5:"))
  prom = numeros(numero_1, numero_2, numero_3, numero_4, numero_5)
  print("El promedio de los 5 numeros es " +str(prom))
  #codigo if que determina el promedio de los números