# -*- coding: utf-8 -*-
"""reto#6.82

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wB-d5kDbUhaIoFO1bo29pe5GSMShBToI
"""

aux_n : float # Se  define la constante, que sera la ayuda para ordenar los numeros
def mediana_(numero_1:float, numero_2:float, numero_3:float, numero_4: float, numero_5: float) -> float:


    if numero_1 < numero_2:
      aux_n = numero_2
      numero_2 = numero_1
      numero_1 = aux_n

    if numero_1 < numero_3:
      aux_n = numero_3
      numero_3 = numero_1
      numero_1 = aux_n

    if numero_1 < numero_3:
      aux_n = numero_3
      numero_3 = numero_1
      numero_1 = aux_n

    if numero_1 < numero_4:
      aux_n = numero_4
      numero_4 = numero_1
      numero_1 = aux_n

    if numero_1 < numero_5:
      aux_n = numero_5
      numero_5 = numero_1
      numero_1 = aux_n

    if numero_2 < numero_3:
      aux_n = numero_3
      numero_3 = numero_2
      numero_2 = aux_n

    if numero_2 < numero_4:
      aux_n = numero_4
      numero_4 = numero_2
      numero_2 = aux_n

    if numero_2 < numero_4:
      aux_n = numero_4
      numero_4 = numero_2
      numero_2 = aux_n

    if numero_2 < numero_5:
      aux_n = numero_5
      numero_5 = numero_2
      numero_2 = aux_n

    if numero_3 < numero_4:
      aux_n = numero_4
      numero_4 = numero_3
      numero_3 = aux_n

    if numero_3 < numero_5:
      aux_n = numero_5
      numero_5 = numero_3
      numero_3 = aux_n

    if numero_4 < numero_5:
      aux_n = numero_5
      numero_5 = numero_4
      numero_4 = aux_n

    return str(numero_3)
    #Se definio una variable que imprime la mediana de los datos

if __name__ == "__main__":
  numero_1 = float(input("Ingresa el número 1:"))
  numero_2 = float(input("Ingresa el número 2:"))
  numero_3 = float(input("Ingresa el número 3:"))
  numero_4 = float(input("Ingresa el número 4:"))
  numero_5 = float(input("Ingresa el número 5:"))
  mediana = mediana_(numero_1, numero_2, numero_3, numero_4, numero_5)
  print("La mediana es  " +str(mediana))
  #codigo if que determina la mediana de los datos